apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Variable environment
on:
  workflow_dispatch:
env:
  ENV: gpm-qa
jobs:
  build:
    environment: ${{ env.ENV }}
    steps:
      - uses: docker://golang:1.20.3-alpine3.17
        name: Say hello
        kind: deploy
        shell: sh
        run: |
          echo "hello world"
